### ISSUE TITLE
Project does not compile

### ISSUE THREAD

**Issue by JimGaluska** [chmorgan/esphttpd-freertos#22]
I can not get the stock project to compile targeting the ESP32.  I am using git commit 2cd29cb of this project and the release/v4.0 branch of the ESP-IDF @ 463a9d8.

**Procedure to reproduce:** 
1.  Clone the repository, cd into the new folder and run the git submodule update command specified in the README
2.  Run ```make```
3.  Once the 'menuconfig' menu appears, change nothing, just save the default config and exit

The following error will occur:
```sh
AR build/espcoredump/libespcoredump.a
CC build/espfs/src/espfs.o
CC build/espfs/src/espfs_vfs.o
CC build/espfs/heatshrink/src/heatshrink_decoder.o
▐ ╢░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░╟
WARN engine uglifycss@0.0.29: wanted: {"node":">=6.4.0"} (current: {"node":"4.2.6","npm":"3.5.2"})
WARN engine @babel/core@7.8.3: wanted: {"node":">=6.9.0"} (current: {"node":"4.2.6","npm":"3.5.2"})
WARN engine html-minifier@4.0.0: wanted: {"node":">=6"} (current: {"node":"4.2.6","npm":"3.5.2"})
WARN engine uglifycss@0.0.29: wanted: {"node":">=6.4.0"} (current: {"node":"4.2.6","npm":"3.5.2"})
WARN engine @babel/core@7.8.3: wanted: {"node":">=6.9.0"} (current: {"node":"4.2.6","npm":"3.5.2"})
loadDep:chokidar → 304    ▌ ╢█████████████████████░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░╟
loadDep:chokidar → resolv ▄ ╢█████████████████████░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░╟
WARN engine make-dir@2.1.0: wanted: {"node":">=6"} (current: {"node":"4.2.6","npm":"3.5.2"})
loadDep:urix → request    ▄ ╢█████████████████████░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░╟
loadDep:semver → request  ▀ ╢███████████████████████░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░╟
loadDep:resolve → addName ▌ ╢████████████████████████░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░╟
WARN engine gensync@1.0.0-beta.1: wanted: {"node":">=6.9.0"} (current: {"node":"4.2.6","npm":"3.5.2"})
WARN engine @babel/parser@7.8.3: wanted: {"node":">=6.0.0"} (current: {"node":"4.2.6","npm":"3.5.2"})
loadDep:levenary → resolv ▄ ╢███████████████████████████░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░╟
loadDep:leven → request   ▐ ╢███████████████████████████░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░╟
npm WARN saveError ENOENT: no such file or directory, open '/home/jgaluska/develop/esp32/esphttpd-freertos/build/espfs/package.json'
/home/jgaluska/develop/esp32/esphttpd-freertos/build/espfs
├─┬ @babel/cli@7.8.3 
│ ├─┬ chokidar@2.1.8 
│ │ ├─┬ anymatch@2.0.0 
│ │ │ ├─┬ micromatch@3.1.10 
│ │ │ │ ├── arr-diff@4.0.0 
│ │ │ │ ├─┬ define-property@2.0.2 
│ │ │ │ │ └─┬ is-descriptor@1.0.2 
│ │ │ │ │   ├── is-accessor-descriptor@1.0.0 
│ │ │ │ │   └── is-data-descriptor@1.0.0 
│ │ │ │ ├─┬ extend-shallow@3.0.2 
│ │ │ │ │ ├── assign-symbols@1.0.0 
│ │ │ │ │ └─┬ is-extendable@1.0.1 
│ │ │ │ │   └── is-plain-object@2.0.4 
│ │ │ │ ├─┬ extglob@2.0.4 
│ │ │ │ │ ├─┬ define-property@1.0.0 
│ │ │ │ │ │ └─┬ is-descriptor@1.0.2 
│ │ │ │ │ │   ├── is-accessor-descriptor@1.0.0 
│ │ │ │ │ │   └── is-data-descriptor@1.0.0 
│ │ │ │ │ ├─┬ expand-brackets@2.1.4 
│ │ │ │ │ │ ├── define-property@0.2.5 
│ │ │ │ │ │ ├── extend-shallow@2.0.1 
│ │ │ │ │ │ └── posix-character-classes@0.1.1 
│ │ │ │ │ └── extend-shallow@2.0.1 
│ │ │ │ ├── fragment-cache@0.2.1 
│ │ │ │ ├── kind-of@6.0.2 
│ │ │ │ ├─┬ nanomatch@1.2.13 
│ │ │ │ │ └── is-windows@1.0.2 
│ │ │ │ ├── object.pick@1.3.0 
│ │ │ │ └── regex-not@1.0.2 
│ │ │ └─┬ normalize-path@2.1.1 
│ │ │   └── remove-trailing-separator@1.1.0 
│ │ ├── async-each@1.0.3 
│ │ ├─┬ braces@2.3.2 
│ │ │ ├── arr-flatten@1.1.0 
│ │ │ ├── array-unique@0.3.2 
│ │ │ ├─┬ extend-shallow@2.0.1 
│ │ │ │ └── is-extendable@0.1.1 
│ │ │ ├─┬ fill-range@4.0.0 
│ │ │ │ ├── extend-shallow@2.0.1 
│ │ │ │ ├─┬ is-number@3.0.0 
│ │ │ │ │ └─┬ kind-of@3.2.2 
│ │ │ │ │   └── is-buffer@1.1.6 
│ │ │ │ ├── repeat-string@1.6.1 
│ │ │ │ └── to-regex-range@2.1.1 
│ │ │ ├── isobject@3.0.1 
│ │ │ ├── repeat-element@1.1.3 
│ │ │ ├─┬ snapdragon@0.8.2 
│ │ │ │ ├─┬ base@0.11.2 
│ │ │ │ │ ├─┬ cache-base@1.0.1 
│ │ │ │ │ │ ├─┬ collection-visit@1.0.0 
│ │ │ │ │ │ │ ├── map-visit@1.0.0 
│ │ │ │ │ │ │ └── object-visit@1.0.1 
│ │ │ │ │ │ ├── get-value@2.0.6 
│ │ │ │ │ │ ├─┬ has-value@1.0.0 
│ │ │ │ │ │ │ └─┬ has-values@1.0.0 
│ │ │ │ │ │ │   └── kind-of@4.0.0 
│ │ │ │ │ │ ├─┬ set-value@2.0.1 
│ │ │ │ │ │ │ └── extend-shallow@2.0.1 
│ │ │ │ │ │ ├─┬ to-object-path@0.3.0 
│ │ │ │ │ │ │ └── kind-of@3.2.2 
│ │ │ │ │ │ ├── union-value@1.0.1 
│ │ │ │ │ │ └─┬ unset-value@1.0.0 
│ │ │ │ │ │   └─┬ has-value@0.3.1 
│ │ │ │ │ │     ├── has-values@0.1.4 
│ │ │ │ │ │     └── isobject@2.1.0 
│ │ │ │ │ ├─┬ class-utils@0.3.6 
│ │ │ │ │ │ ├── arr-union@3.1.0 
│ │ │ │ │ │ ├── define-property@0.2.5 
│ │ │ │ │ │ └─┬ static-extend@0.1.2 
│ │ │ │ │ │   ├── define-property@0.2.5 
│ │ │ │ │ │   └─┬ object-copy@0.1.0 
│ │ │ │ │ │     ├── copy-descriptor@0.1.1 
│ │ │ │ │ │     ├── define-property@0.2.5 
│ │ │ │ │ │     └── kind-of@3.2.2 
│ │ │ │ │ ├── component-emitter@1.3.0 
│ │ │ │ │ ├─┬ define-property@1.0.0 
│ │ │ │ │ │ └─┬ is-descriptor@1.0.2 
│ │ │ │ │ │   ├── is-accessor-descriptor@1.0.0 
│ │ │ │ │ │   └── is-data-descriptor@1.0.0 
│ │ │ │ │ ├─┬ mixin-deep@1.3.2 
│ │ │ │ │ │ ├── for-in@1.0.2 
│ │ │ │ │ │ └── is-extendable@1.0.1 
│ │ │ │ │ └── pascalcase@0.1.1 
│ │ │ │ ├─┬ debug@2.6.9 
│ │ │ │ │ └── ms@2.0.0 
│ │ │ │ ├─┬ define-property@0.2.5 
│ │ │ │ │ └─┬ is-descriptor@0.1.6 
│ │ │ │ │   ├─┬ is-accessor-descriptor@0.1.6 
│ │ │ │ │   │ └── kind-of@3.2.2 
│ │ │ │ │   ├─┬ is-data-descriptor@0.1.4 
│ │ │ │ │   │ └── kind-of@3.2.2 
│ │ │ │ │   └── kind-of@5.1.0 
│ │ │ │ ├── extend-shallow@2.0.1 
│ │ │ │ ├── map-cache@0.2.2 
│ │ │ │ ├─┬ source-map-resolve@0.5.3 
│ │ │ │ │ ├── atob@2.1.2 
│ │ │ │ │ ├── decode-uri-component@0.2.0 
│ │ │ │ │ ├── resolve-url@0.2.1 
│ │ │ │ │ ├── source-map-url@0.4.0 
│ │ │ │ │ └── urix@0.1.0 
│ │ │ │ └── use@3.1.1 
│ │ │ ├─┬ snapdragon-node@2.1.1 
│ │ │ │ ├─┬ define-property@1.0.0 
│ │ │ │ │ └─┬ is-descriptor@1.0.2 
│ │ │ │ │   ├── is-accessor-descriptor@1.0.0 
│ │ │ │ │   └── is-data-descriptor@1.0.0 
│ │ │ │ └─┬ snapdragon-util@3.0.1 
│ │ │ │   └── kind-of@3.2.2 
│ │ │ ├── split-string@3.1.0 
│ │ │ └─┬ to-regex@3.0.2 
│ │ │   └─┬ safe-regex@1.1.0 
│ │ │     └── ret@0.1.15 
│ │ ├─┬ glob-parent@3.1.0 
│ │ │ ├── is-glob@3.1.0 
│ │ │ └── path-dirname@1.0.2 
│ │ ├── inherits@2.0.4 
│ │ ├─┬ is-binary-path@1.0.1 
│ │ │ └── binary-extensions@1.13.1 
│ │ ├─┬ is-glob@4.0.1 
│ │ │ └── is-extglob@2.1.1 
│ │ ├── normalize-path@3.0.0 
│ │ ├── path-is-absolute@1.0.1 
│ │ ├─┬ readdirp@2.2.1 
│ │ │ ├── graceful-fs@4.2.3 
│ │ │ └─┬ readable-stream@2.3.7 
│ │ │   ├── core-util-is@1.0.2 
│ │ │   ├── isarray@1.0.0 
│ │ │   ├── process-nextick-args@2.0.1 
│ │ │   ├── string_decoder@1.1.1 
│ │ │   └── util-deprecate@1.0.2 
│ │ └── upath@1.2.0 
│ ├── commander@4.1.0 
│ ├─┬ convert-source-map@1.7.0 
│ │ └── safe-buffer@5.1.2 
│ ├── fs-readdir-recursive@1.1.0 
│ ├─┬ glob@7.1.6 
│ │ ├── fs.realpath@1.0.0 
│ │ ├─┬ inflight@1.0.6 
│ │ │ └── wrappy@1.0.2 
│ │ ├─┬ minimatch@3.0.4 
│ │ │ └─┬ brace-expansion@1.1.11 
│ │ │   ├── balanced-match@1.0.0 
│ │ │   └── concat-map@0.0.1 
│ │ └── once@1.4.0 
│ ├── lodash@4.17.15 
│ ├─┬ make-dir@2.1.0 
│ │ └── pify@4.0.1 
│ ├── slash@2.0.0 
│ └── source-map@0.5.7 
├─┬ @babel/core@7.8.3 
│ ├─┬ @babel/code-frame@7.8.3 
│ │ └─┬ @babel/highlight@7.8.3 
│ │   ├─┬ chalk@2.4.2 
│ │   │ ├─┬ ansi-styles@3.2.1 
│ │   │ │ └─┬ color-convert@1.9.3 
│ │   │ │   └── color-name@1.1.3 
│ │   │ ├── escape-string-regexp@1.0.5 
│ │   │ └─┬ supports-color@5.5.0 
│ │   │   └── has-flag@3.0.0 
│ │   └── js-tokens@4.0.0 
│ ├─┬ @babel/generator@7.8.3 
│ │ └── jsesc@2.5.2 
│ ├── @babel/helpers@7.8.3 
│ ├── @babel/parser@7.8.3 
│ ├── @babel/template@7.8.3 
│ ├─┬ @babel/traverse@7.8.3 
│ │ ├── @babel/helper-function-name@7.8.3 
│ │ ├── @babel/helper-split-export-declaration@7.8.3 
│ │ ├─┬ debug@4.1.1 
│ │ │ └── ms@2.1.2 
│ │ └── globals@11.12.0 
│ ├─┬ @babel/types@7.8.3 
│ │ ├── esutils@2.0.3 
│ │ └── to-fast-properties@2.0.0 
│ ├─┬ debug@4.1.1 
│ │ └── ms@2.1.2 
│ ├── gensync@1.0.0-beta.1 
│ ├─┬ json5@2.1.1 
│ │ └── minimist@1.2.0 
│ ├─┬ resolve@1.14.2 
│ │ └── path-parse@1.0.6 
│ └── semver@5.7.1 
├─┬ @babel/preset-env@7.8.3 
│ ├── @babel/compat-data@7.8.1 
│ ├── @babel/helper-compilation-targets@7.8.3 
│ ├── @babel/helper-module-imports@7.8.3 
│ ├── @babel/helper-plugin-utils@7.8.3 
│ ├─┬ @babel/plugin-proposal-async-generator-functions@7.8.3 
│ │ └─┬ @babel/helper-remap-async-to-generator@7.8.3 
│ │   └── @babel/helper-wrap-function@7.8.3 
│ ├── @babel/plugin-proposal-dynamic-import@7.8.3 
│ ├── @babel/plugin-proposal-json-strings@7.8.3 
│ ├── @babel/plugin-proposal-nullish-coalescing-operator@7.8.3 
│ ├── @babel/plugin-proposal-object-rest-spread@7.8.3 
│ ├── @babel/plugin-proposal-optional-catch-binding@7.8.3 
│ ├── @babel/plugin-proposal-optional-chaining@7.8.3 
│ ├─┬ @babel/plugin-proposal-unicode-property-regex@7.8.3 
│ │ └─┬ @babel/helper-create-regexp-features-plugin@7.8.3 
│ │   └─┬ regexpu-core@4.6.0 
│ │     ├── regenerate@1.4.0 
│ │     ├── regenerate-unicode-properties@8.1.0 
│ │     ├── regjsgen@0.5.1 
│ │     ├─┬ regjsparser@0.6.2 
│ │     │ └── jsesc@0.5.0 
│ │     ├─┬ unicode-match-property-ecmascript@1.0.4 
│ │     │ ├── unicode-canonical-property-names-ecmascript@1.0.4 
│ │     │ └── unicode-property-aliases-ecmascript@1.0.5 
│ │     └── unicode-match-property-value-ecmascript@1.1.0 
│ ├── @babel/plugin-syntax-async-generators@7.8.4 
│ ├── @babel/plugin-syntax-dynamic-import@7.8.3 
│ ├── @babel/plugin-syntax-json-strings@7.8.3 
│ ├── @babel/plugin-syntax-nullish-coalescing-operator@7.8.3 
│ ├── @babel/plugin-syntax-object-rest-spread@7.8.3 
│ ├── @babel/plugin-syntax-optional-catch-binding@7.8.3 
│ ├── @babel/plugin-syntax-optional-chaining@7.8.3 
│ ├── @babel/plugin-syntax-top-level-await@7.8.3 
│ ├── @babel/plugin-transform-arrow-functions@7.8.3 
│ ├── @babel/plugin-transform-async-to-generator@7.8.3 
│ ├── @babel/plugin-transform-block-scoped-functions@7.8.3 
│ ├── @babel/plugin-transform-block-scoping@7.8.3 
│ ├─┬ @babel/plugin-transform-classes@7.8.3 
│ │ ├── @babel/helper-annotate-as-pure@7.8.3 
│ │ ├── @babel/helper-define-map@7.8.3 
│ │ ├── @babel/helper-optimise-call-expression@7.8.3 
│ │ └─┬ @babel/helper-replace-supers@7.8.3 
│ │   └── @babel/helper-member-expression-to-functions@7.8.3 
│ ├── @babel/plugin-transform-computed-properties@7.8.3 
│ ├── @babel/plugin-transform-destructuring@7.8.3 
│ ├── @babel/plugin-transform-dotall-regex@7.8.3 
│ ├── @babel/plugin-transform-duplicate-keys@7.8.3 
│ ├─┬ @babel/plugin-transform-exponentiation-operator@7.8.3 
│ │ └─┬ @babel/helper-builder-binary-assignment-operator-visitor@7.8.3 
│ │   └── @babel/helper-explode-assignable-expression@7.8.3 
│ ├── @babel/plugin-transform-for-of@7.8.3 
│ ├── @babel/plugin-transform-function-name@7.8.3 
│ ├── @babel/plugin-transform-literals@7.8.3 
│ ├── @babel/plugin-transform-member-expression-literals@7.8.3 
│ ├─┬ @babel/plugin-transform-modules-amd@7.8.3 
│ │ ├── @babel/helper-module-transforms@7.8.3 
│ │ └─┬ babel-plugin-dynamic-import-node@2.3.0 
│ │   └─┬ object.assign@4.1.0 
│ │     ├── define-properties@1.1.3 
│ │     ├── function-bind@1.1.1 
│ │     ├── has-symbols@1.0.1 
│ │     └── object-keys@1.1.1 
│ ├─┬ @babel/plugin-transform-modules-commonjs@7.8.3 
│ │ └── @babel/helper-simple-access@7.8.3 
│ ├─┬ @babel/plugin-transform-modules-systemjs@7.8.3 
│ │ └── @babel/helper-hoist-variables@7.8.3 
│ ├── @babel/plugin-transform-modules-umd@7.8.3 
│ ├── @babel/plugin-transform-named-capturing-groups-regex@7.8.3 
│ ├── @babel/plugin-transform-new-target@7.8.3 
│ ├── @babel/plugin-transform-object-super@7.8.3 
│ ├─┬ @babel/plugin-transform-parameters@7.8.3 
│ │ ├── @babel/helper-call-delegate@7.8.3 
│ │ └── @babel/helper-get-function-arity@7.8.3 
│ ├── @babel/plugin-transform-property-literals@7.8.3 
│ ├─┬ @babel/plugin-transform-regenerator@7.8.3 
│ │ └─┬ regenerator-transform@0.14.1 
│ │   └── private@0.1.8 
│ ├── @babel/plugin-transform-reserved-words@7.8.3 
│ ├── @babel/plugin-transform-shorthand-properties@7.8.3 
│ ├── @babel/plugin-transform-spread@7.8.3 
│ ├─┬ @babel/plugin-transform-sticky-regex@7.8.3 
│ │ └── @babel/helper-regex@7.8.3 
│ ├── @babel/plugin-transform-template-literals@7.8.3 
│ ├── @babel/plugin-transform-typeof-symbol@7.8.3 
│ ├── @babel/plugin-transform-unicode-regex@7.8.3 
│ ├─┬ browserslist@4.8.3 
│ │ ├── caniuse-lite@1.0.30001021 
│ │ ├── electron-to-chromium@1.3.335 
│ │ └─┬ node-releases@1.1.45 
│ │   └── semver@6.3.0 
│ ├─┬ core-js-compat@3.6.4 
│ │ └── semver@7.0.0 
│ ├─┬ invariant@2.2.4 
│ │ └── loose-envify@1.4.0 
│ └─┬ levenary@1.1.0 
│   └── leven@3.1.0 
├─┬ babel-preset-minify@0.5.1 
│ ├── babel-plugin-minify-builtins@0.5.0 
│ ├─┬ babel-plugin-minify-constant-folding@0.5.0 
│ │ └── babel-helper-evaluate-path@0.5.0 
│ ├─┬ babel-plugin-minify-dead-code-elimination@0.5.1 
│ │ ├── babel-helper-mark-eval-scopes@0.4.3 
│ │ └── babel-helper-remove-or-void@0.4.3 
│ ├─┬ babel-plugin-minify-flip-comparisons@0.4.3 
│ │ └── babel-helper-is-void-0@0.4.3 
│ ├─┬ babel-plugin-minify-guarded-expressions@0.4.4 
│ │ └── babel-helper-flip-expressions@0.4.3 
│ ├── babel-plugin-minify-infinity@0.4.3 
│ ├── babel-plugin-minify-mangle-names@0.5.0 
│ ├── babel-plugin-minify-numeric-literals@0.4.3 
│ ├── babel-plugin-minify-replace@0.5.0 
│ ├─┬ babel-plugin-minify-simplify@0.5.1 
│ │ ├── babel-helper-is-nodes-equiv@0.0.1 
│ │ └── babel-helper-to-multiple-sequence-expressions@0.5.0 
│ ├── babel-plugin-minify-type-constructors@0.4.3 
│ ├── babel-plugin-transform-inline-consecutive-adds@0.4.3 
│ ├── babel-plugin-transform-member-expression-literals@6.9.4 
│ ├── babel-plugin-transform-merge-sibling-variables@6.9.4 
│ ├── babel-plugin-transform-minify-booleans@6.9.4 
│ ├── babel-plugin-transform-property-literals@6.9.4 
│ ├── babel-plugin-transform-regexp-constructors@0.4.3 
│ ├── babel-plugin-transform-remove-console@6.9.4 
│ ├── babel-plugin-transform-remove-debugger@6.9.4 
│ ├── babel-plugin-transform-remove-undefined@0.5.0 
│ ├── babel-plugin-transform-simplify-comparison-operators@6.9.4 
│ └── babel-plugin-transform-undefined-to-void@6.9.4 
├─┬ html-minifier@4.0.0 
│ ├─┬ camel-case@3.0.0 
│ │ ├─┬ no-case@2.3.2 
│ │ │ └── lower-case@1.1.4 
│ │ └── upper-case@1.1.3 
│ ├─┬ clean-css@4.2.1 
│ │ └── source-map@0.6.1 
│ ├── commander@2.20.3 
│ ├── he@1.2.0 
│ ├── param-case@2.1.1 
│ ├── relateurl@0.2.7 
│ └─┬ uglify-js@3.7.5 
│   ├── commander@2.20.3 
│   └── source-map@0.6.1 
└── uglifycss@0.0.29 

npm WARN optional Skipping failed optional dependency /chokidar/fsevents:
npm WARN notsup Not compatible with your operating system or architecture: fsevents@1.2.11
npm WARN enoent ENOENT: no such file or directory, open '/home/jgaluska/develop/esp32/esphttpd-freertos/build/espfs/package.json'
npm WARN espfs No description
npm WARN espfs No repository field.
npm WARN espfs No README data
npm WARN espfs No license field.
Traceback (most recent call last):
  File "/home/jgaluska/develop/esp32/esphttpd-freertos/components/espfs/tools/build-image.py", line 36, in <module>
    os.mkdir(dest)
TypeError: mkdir: illegal type for path parameter
/home/jgaluska/develop/esp32/esphttpd-freertos/components/espfs/component.mk:70: recipe for target 'espfs_image.bin' failed
make[1]: *** [espfs_image.bin] Error 1
/home/jgaluska/esp-idf/make/project.mk:590: recipe for target 'component-espfs-build' failed
make: *** [component-espfs-build] Error 2

```

**Comment by phatpaul** [comment]
I can confirm, can no longer build on my setup either.  Error is python3 can't be found.

@jkent I think we need to support building on any platform/environment that Espressif currently supports, including make on msys2.

**Comment by phatpaul** [comment]
@JimGaluska this was broken in the last commit https://github.com/chmorgan/esphttpd-freertos/commit/2cd29cb7c25536da93a5258aa3f6414dcabed79b

You could revert to the previous version until we figure out how to fix it:  (use --force if git complains)
```
git checkout 5f449df67140f6e183c465edc8b32e8d399b14e7
git submodule update --init --recursive
```

**Comment by jkent** [comment]
I forgot about this.  Its due to IDF using its packaged version of python 2.7 which doesn't have pathlib.  I'll work a version of the script that uses the legacy path functions this afternoon.

**Comment by jkent** [comment]
OK, I've fixed the python issue, https://github.com/jkent/esp32-espfs/tree/python-path-compat but there is more to do as we've diverged somewhere... I'll work on it more this evening.

**Comment by phatpaul** [comment]
note I had to change the first line of build-image.py from 
`#!/usr/bin/env python3`
to `#!/usr/bin/env python` to allow it to build on my msys2 ESP-IDF 3.3.

**Comment by jkent** [comment]
OK, I've got it to build... Looks like the libesphttpd submodule needs to be bumped too.

**Comment by JimGaluska** [comment]
You guys are really responsive, Thanks! It gives me confidence to use your library.  

I have had my attention diverted for the last few days, however I just confirmed that commit #5f449d compiles and works as expected.

I also noticed that the commit ID of submodule espfs moved from b87f89a to dd2d57d.  The APIs of espfs changed their interface and this change did ripple across to this library.  This also would cause a compilation error.  @jkent, Is this one of the changes you mentions above?  Let me know if it isn't so that I can write this up in a separate issue.

**Comment by jkent** [comment]
It was, yes.  It didn't help that I haven't had my eyes on this code since October.  The API changed to support multiple espfs filesystems.  You can have one linked into the binary and one stored in a partition at the same time now.  Right now I'm working through a windows build issue, then we will get synced up.

**Comment by jkent** [comment]
@phatpaul I think we're better off with Windows now.  I do have an issue with mkespfsimage -- I need to port this tool from C to python so we don't have to worry about the user having ming32 or visual studio toolchain around.  Its not even possible to build with visual studio because of unistd.h.

**Comment by jkent** [comment]
I take that back about porting mkespfsimage... maybe we should just bundle a windows binary.  I forgot about heatshrink as a dependency, and while there are bindings, we'd still need a compiler for the bindings.
